import { 
  Zap, 
  Activity, 
  Megaphone, 
  Layers, 
  MessageCircle, 
  X, 
  Plus, 
  Search, 
  Bell, 
  FileText, 
  Users, 
  MapPin, 
  Clock, 
  List, 
  Share, 
  Award, 
  Link, 
  CheckSquare, 
  Upload, 
  UserPlus, 
  ExternalLink,
  Download,
  Gavel,
  ChevronRight,
  TrendingUp,
  BarChart2,
  BarChart,
  Clipboard,
  Edit,
  Pause,
  Trash,
  Play,
  Check,
  AlertCircle,
  MessageSquare
} from "lucide-react";

export const icons = {
  zap: Zap,
  activity: Activity,
  megaphone: Megaphone,
  layers: Layers,
  messageCircle: MessageCircle,
  x: X,
  plus: Plus,
  search: Search,
  bell: Bell,
  fileText: FileText,
  users: Users,
  mapPin: MapPin,
  clock: Clock,
  list: List,
  share: Share,
  award: Award,
  link: Link,
  checkSquare: CheckSquare,
  upload: Upload,
  userPlus: UserPlus,
  externalLink: ExternalLink,
  download: Download,
  gavel: Gavel,
  chevronRight: ChevronRight,
  trendingUp: TrendingUp,
  barChart2: BarChart2,
  barChart: BarChart,
  clipboard: Clipboard,
  edit: Edit,
  pause: Pause,
  trash: Trash,
  play: Play,
  check: Check,
  alertCircle: AlertCircle,
  messageSquare: MessageSquare
};

export function Icon({ name, size = 18, className = "" }: { name: keyof typeof icons, size?: number, className?: string }) {
  const LucideIcon = icons[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} className={className} />;
}
