import { chromium } from '@playwright/test';
// Browser walkthrough of the PS flow against scripts/ps-fake-supabase.mjs (synthetic data).
// See HANDOVER.md for how to start the fake backend and dev server first.
const BASE = process.env.PS_E2E_BASE || 'http://127.0.0.1:4173', OUT = process.env.PS_E2E_OUT || 'test-results/ps-e2e';
import fs from 'node:fs'; fs.mkdirSync(OUT, { recursive: true });
const TID = '4a16320d-5ccc-4e53-aaca-b9033af9371c';
const user = { id: '11111111-1111-4111-8111-111111111111', email: 'synthetic-owner@example.test', aud: 'authenticated', role: 'authenticated', user_metadata: {} };
const session = { access_token: 'synthetic-token', refresh_token: 'r', token_type: 'bearer', expires_in: 360000, expires_at: Math.floor(Date.now() / 1000) + 360000, user };
const browser = await chromium.launch({ ...(process.env.PS_E2E_CHROMIUM ? { executablePath: process.env.PS_E2E_CHROMIUM } : {}) });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await ctx.newPage();
const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => m.type() === 'error' && errors.push(m.text()));
page.on('dialog', d => d.accept('Synthetic test override'));
await page.goto(BASE + '/');
await page.evaluate(([s, t]) => { localStorage.setItem('sb-127-auth-token', JSON.stringify(s)); localStorage.setItem('active_tournament_id', t); }, [session, TID]);
await page.goto(BASE + '/#/tournament/public-speaking');
await page.waitForSelector('form[data-form="settings"]', { timeout: 15000 });
await page.selectOption('select[name="preset"]', 'prepared');
await page.fill('input[name="name"]', 'Synthetic Prepared Speech');
await page.selectOption('select[name="penaltyMethod"]', 'overtime');
await page.waitForSelector('#ps-rule-preview table', { timeout: 5000 });
await page.screenshot({ path: `${OUT}/1-setup.png`, fullPage: true });
console.log('PREVIEW:', (await page.textContent('#ps-rule-preview')).replace(/\s+/g, ' ').slice(0, 400));
// Invalid weights show a clear error in the preview
await page.fill('input[name="criterionWeight"] >> nth=0', '50');
await page.waitForTimeout(900);
console.log('INVALID:', (await page.textContent('#ps-rule-preview')).trim());
await page.fill('input[name="criterionWeight"] >> nth=0', '40');
await page.click('button:has-text("Create event")');
await page.waitForSelector('button:has-text("Add people")', { timeout: 10000 });
const names = Array.from({ length: 12 }, (_, i) => `Synthetic Speaker ${i + 1}\tSchool ${i % 4}\tOpen`).join('\n');
await page.click('button:has-text("Add people")');
await page.fill('#ps-dialog textarea[name="people"]', names);
await page.click('#ps-dialog button[type="submit"]');
await page.waitForSelector('text=Synthetic Speaker 12');
await page.click('button[data-tab="judges"]');
await page.click('button:has-text("Add people")');
await page.fill('#ps-dialog textarea[name="people"]', Array.from({ length: 4 }, (_, i) => `Synthetic Judge ${i + 1}\tJudge Inst ${i}`).join('\n'));
await page.click('#ps-dialog button[type="submit"]');
await page.waitForSelector('text=Synthetic Judge 4');
await page.click('button[data-tab="setup"]');
await page.click('form[data-form="plan"] button[type="submit"]');
await page.waitForSelector('#ps-plan .ps-stats');
console.log('PLAN:', (await page.textContent('#ps-plan')).replace(/\s+/g, ' ').slice(0, 300));
await page.fill('form[data-form="plan"] input[name="entrants"]', '60');
await page.fill('form[data-form="plan"] input[name="judges"]', '10');
await page.click('form[data-form="plan"] button[type="submit"]');
await page.waitForTimeout(800);
console.log('PLAN60:', (await page.textContent('#ps-plan')).replace(/\s+/g, ' ').slice(0, 300));
await page.screenshot({ path: `${OUT}/2-planner.png`, fullPage: true });
// Round + draw
await page.click('button[data-tab="rounds"]');
await page.click('button:has-text("Create round")');
await page.click('#ps-dialog button[type="submit"]');
await page.click('button:has-text("Generate / edit draw")');
await page.click('#ps-dialog [data-generate]');
await page.waitForSelector('#ps-dialog #ps-draw-report section');
console.log('DRAW REPORT:', (await page.textContent('#ps-draw-report')).replace(/\s+/g, ' ').slice(0, 400));
await page.screenshot({ path: `${OUT}/2b-draw.png`, fullPage: true });
await page.click('#ps-dialog button[type="submit"]');
await page.waitForSelector('#ps-dialog', { state: 'detached' });
await page.click('button:has-text("Publish draw")');
await page.waitForSelector('button:has-text("Enter ballot")');
// Judge private link
await page.click('button[data-tab="judges"]');
await page.click('button[data-action="portal"] >> nth=0');
await page.waitForSelector('#ps-dialog');
await page.click('#ps-dialog button[value="create"]');
await page.waitForSelector('#ps-link-result input[name="url"]');
const link = await page.inputValue('#ps-link-result input[name="url"]');
console.log('LINK OK:', /\/ps\/portal\//.test(link));
await page.click('#ps-dialog [data-close]');
const judge = await (await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true })).newPage();
judge.on('pageerror', e => errors.push('portal: ' + e.message));
await judge.goto(link.startsWith('http') ? link : BASE + '/' + link.replace(/^\//, ''));
await judge.waitForSelector('button:has-text("ballot")', { timeout: 10000 });
console.log('CLEAN URL:', !judge.url().includes('psl_'), judge.url().replace(/.*#/, '#'));
await judge.screenshot({ path: `${OUT}/3-judge-portal.png`, fullPage: true });
await judge.click('button[data-action="ballot"]');
const speakers = await judge.locator('#ps-dialog fieldset.ps-ballot-speaker').count();
for (let i = 0; i < speakers; i++) {
  await judge.fill(`#ps-dialog input[name="score-${i}-0"]`, String(30 - i));
  await judge.fill(`#ps-dialog input[name="score-${i}-1"]`, String(28 - i));
  await judge.fill(`#ps-dialog input[name="score-${i}-2"]`, String(20 - i));
  await judge.fill(`#ps-dialog input[name="rank-${i}"]`, String(i + 1));
  await judge.fill(`#ps-dialog input[name="elapsed-${i}"]`, String(i === 1 ? 330 : 290));
  await judge.fill(`#ps-dialog textarea[name="worked-${i}"]`, 'Synthetic: clear structure');
}
await judge.click('#ps-dialog button[value="review"]');
await judge.waitForSelector('#ps-dialog [data-review] table');
console.log('REVIEW:', (await judge.textContent('#ps-dialog [data-review]')).replace(/\s+/g, ' ').slice(0, 300));
await judge.screenshot({ path: `${OUT}/4-ballot-review.png`, fullPage: false });
await judge.locator('#ps-dialog [data-review]').scrollIntoViewIfNeeded();
await judge.screenshot({ path: `${OUT}/4b-ballot-review.png` });
await judge.click('#ps-dialog button[value="submitted"]');
await judge.waitForSelector('#ps-dialog', { state: 'detached', timeout: 10000 });
await page.click('button[data-tab="rounds"]'); await page.click('button:has-text("Refresh")');
await page.waitForTimeout(1000);
await page.click('button:has-text("View") >> nth=0'); await page.waitForSelector('#ps-dialog table');
console.log('ADMIN BALLOT VIEW:', (await page.textContent('#ps-dialog')).replace(/\s+/g, ' ').slice(0, 250)); await page.click('#ps-dialog [data-close]');
console.log('ADMIN SEES:', (await page.textContent('.ps-room table')).replace(/\s+/g, ' ').slice(0, 200));
await page.screenshot({ path: `${OUT}/5-admin-rounds.png`, fullPage: true });
console.log('ERRORS:', JSON.stringify(errors));
await browser.close();
